//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NroIpDatabaseGenerator {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NroIpDatabaseGenerator.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End-User License Agreement (&quot;Agreement&quot;)  
        ///========================================
        ///
        ///Last updated: April 09, 2020
        ///
        ///Please read this End-User License Agreement carefully before clicking the &quot;I
        ///Agree&quot; button, downloading or using NRO Geolocation DB Generator.
        ///
        ///Interpretation and Definitions  
        ///==============================
        ///
        ///Interpretation  
        ///--------------
        ///
        ///The words of which the initial letter is capitalized have meanings defined
        ///under the following conditions.
        ///
        ///The following definitions shall have the same m [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EULA {
            get {
                return ResourceManager.GetString("EULA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ========================================
        ///End-User License Agreement (&quot;Agreement&quot;)  
        ///========================================
        ///
        ///Last updated: April 09, 2020
        ///
        ///Please read this End-User License Agreement carefully before accepting it, and using NRO Geolocation
        ///DB Generator.
        ///
        ///Acknowledgement  
        ///===============
        ///
        ///By typing &quot;I Agree&quot; button, downloading or using the Application, You are agreeing to be bound by the
        ///terms and conditions of this Agreement. If You do not agree to the terms of this Agreement [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EULA_Redacted {
            get {
                return ResourceManager.GetString("EULA_Redacted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Afghanistan,AF
        ///Falkland Islands,AX
        ///Albania,AL
        ///Algeria,DZ
        ///American Samoa,AS
        ///Andorra,AD
        ///Angola,AO
        ///Anguilla,AI
        ///Antarctica,AQ
        ///Antigua and Barbuda,AG
        ///Argentina,AR
        ///Armenia,AM
        ///Aruba,AW
        ///Australia,AU
        ///Austria,AT
        ///Azerbaijan,AZ
        ///Bahamas,BS
        ///Bahrain,BH
        ///Bangladesh,BD
        ///Barbados,BB
        ///Belarus,BY
        ///Belgium,BE
        ///Belize,BZ
        ///Benin,BJ
        ///Bermuda,BM
        ///Bhutan,BT
        ///&quot;Bolivia, Plurinational State of&quot;,BO
        ///&quot;Bonaire, Sint Eustatius and Saba&quot;,BQ
        ///Bosnia and Herzegovina,BA
        ///Botswana,BW
        ///Bouvet Island,BV
        ///Brazil,BR
        ///British Indian [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string IsoAlpha2CountryCodes {
            get {
                return ResourceManager.GetString("IsoAlpha2CountryCodes", resourceCulture);
            }
        }
    }
}
